# Generated by Django 4.0.1 on 2022-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_tutorial_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='visite',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
