# Generated by Django 4.0.1 on 2022-09-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default='https://', max_length=210),
        ),
    ]
